# Generated by Django 4.2 on 2023-04-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='flashcardsset',
            name='slug',
            field=models.SlugField(default='', max_length=96, unique=True),
        ),
    ]
