# Generated by Django 4.2 on 2023-04-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_flashcard_author_alter_flashcardsset_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(default='test', max_length=1),
            preserve_default=False,
        ),
    ]
