# Generated by Django 4.2 on 2023-04-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_quizanswer_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='letter',
            field=models.CharField(default='N', max_length=1),
            preserve_default=False,
        ),
    ]
