# Generated by Django 4.2 on 2023-04-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_quizanswer_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardsset',
            name='slug',
        ),
    ]
